name: Run tests on staging
on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ODAN_SANDBOX_BOT_APP_ID }}
          private-key: ${{ secrets.ODAN_SANDBOX_BOT_PRIVATE_KEY }}

      - name: Download git-pr-release-go
        uses: KeisukeYamashita/setup-release@v1.0.2
        with:
          repository: odanado/git-pr-release-go
          arch: x86_64
          tag: v0.0.3
        env:
          GH_TOKEN: ${{ github.token }}

      - run: git-pr-release-go --help

      - run: git-pr-release-go --from main --to release/test
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
