name: Run tests on staging
on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ODAN_SANDBOX_BOT_APP_ID }}
          private-key: ${{ secrets.ODAN_SANDBOX_BOT_PRIVATE_KEY }}
          