name: Create Release Pull Request
on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Download git-pr-release-go
        uses: KeisukeYamashita/setup-release@v1.0.2
        with:
          repository: odanado/git-pr-release-go
          arch: x86_64
          platform: "Linux"
        env:
          GH_TOKEN: ${{ github.token }}

      - run: ./git-pr-release-go --from main --to release/test3
        working-directory: git-pr-release-go
        env:
          GITHUB_TOKEN: ${{ github.token }}
