name: Create Release Pull Request (release/test3)
on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Download git-pr-release-go
        uses: KeisukeYamashita/setup-release@v1.0.2
        with:
          repository: odanado/git-pr-release-go
          arch: x86_64
          platform: "Linux"
        env:
          GH_TOKEN: ${{ github.token }}

      - run: git-pr-release-go --help

      - run: git-pr-release-go --from main --to release/test3
        env:
          GITHUB_TOKEN: ${{ github.token }}
